// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcvqvyxtgakelauvmuno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjdnF2eXh0Z2FrZWxhdXZtdW5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDczODgsImV4cCI6MjA2ODI4MzM4OH0.J5bzPD2TXOMoZgx9u5s_9aVvm0ZB7Fh0T2K1mMwIVBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});