// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpvjdkcwpbpbbjkwlxvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhwdmpka2N3cGJwYmJqa3dseHZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzODQ0MzYsImV4cCI6MjA4Njk2MDQzNn0.HC7E4eqMJB-hnh7_TB8dTagGEvo9ZizRlZRyV6N3p0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});